INSERT INTO quote (text) VALUES ('Dream big! But maybe keep a bucket of reality nearby in case things get too fluffy');
INSERT INTO quote (text) VALUES ('You’re capable of amazing things… assuming you’ve had three coffees and a deadline in ten minutes.');
INSERT INTO quote (text) VALUES ('Be the rainbow in someone’s cloud… or just be the cloud. Everyone needs an excuse to stay indoors.');
INSERT INTO quote (text) VALUES ('The early bird gets the worm, but the second mouse gets the cheese. Choose your hustle wisely.');
INSERT INTO quote (text) VALUES ('Follow your dreams! Or don’t. They’ll probably just lead you to a parking ticket and existential dread.');
INSERT INTO quote (text) VALUES ('Rise and grind! Or just rise. Grinding is optional—naps are forever.');
INSERT INTO quote (text) VALUES ('You’re a star! A collapsing neutron star, but still… shiny');
INSERT INTO quote (text) VALUES ('Every day is a gift! Unless it’s Monday. Monday is the receipt you forgot to return');
INSERT INTO quote (text) VALUES ('Believe in yourself! Or hire someone to do it for you. Delegation is key.');
INSERT INTO quote (text) VALUES ('Success is 1% inspiration, 99% Googling how to adult.');
INSERT INTO quote (text) VALUES ('You’re enough! But if you’re bored, feel free to overcompensate.');
INSERT INTO quote (text) VALUES ('Embrace failure! It’s like success, but with better stories.');
INSERT INTO quote (text) VALUES ('Be the change you wish to see… or just wait for someone else to do it. Sustainability matters.');
INSERT INTO quote (text) VALUES ('Shoot for the moon! If you miss, you’ll land in a pile of unpaid bills and unanswered emails.');
INSERT INTO quote (text) VALUES ('Hustle culture is overrated. Have you tried existential napping?');
INSERT INTO quote (text) VALUES ('You’re not lazy—you’re just energy-efficient. Save the planet, one couch day at a time.');
INSERT INTO quote (text) VALUES ('Life is short! But don’t worry, Mondays make it feel infinitely longer.');
INSERT INTO quote (text) VALUES ('Turn your wounds into wisdom! Or just into memes. Profit either way.');
INSERT INTO quote (text) VALUES ('You can’t pour from an empty cup… but you can refill it with sarcasm and caffeine.');
INSERT INTO quote (text) VALUES ('Be the reason someone smiles today… or the reason they roll their eyes. Participation counts.');
INSERT INTO quote (text) VALUES ('Failure is just success rounded down. Or up. Honestly, math was never my strength.');
INSERT INTO quote (text) VALUES ('The best revenge is massive success! Or a well-timed ‘I told you so.’ Your call.');
INSERT INTO quote (text) VALUES ('Stay positive! Your aura is probably just blinding people to your chaos.');
INSERT INTO quote (text) VALUES ('If opportunity doesn’t knock, build a door. Or just order takeout. Opportunity loves dumplings.');
INSERT INTO quote (text) VALUES ('You’re a limited edition! Mostly because no one else wants this much chaos');
INSERT INTO quote (text) VALUES ('The only way to do great work is to love what you do… or be great at faking it for the paycheck.');
INSERT INTO quote (text) VALUES ('Don’t stop until you’re proud! Or until the Wi-Fi cuts out. Priorities.');
INSERT INTO quote (text) VALUES ('She believed she could, so she did… until she realized ‘could’ required a 12-step tutorial.');
INSERT INTO quote (text) VALUES ('Your vibe attracts your tribe! Unless your vibe is "please stop talking."');
INSERT INTO quote (text) VALUES ('Work hard in silence. Let success make the noise… or let your neighbor’s dog do it at 3 a.m.');
INSERT INTO quote (text) VALUES ('You’re not stuck—you’re just marinating in character development. Congrats, protagonist!');
INSERT INTO quote (text) VALUES ('The only thing standing between you and your goal is… probably your own poor life choices.');
INSERT INTO quote (text) VALUES ('Be yourself! Unless you can be a nap. Always be the nap.');
